### ISSUE TITLE
About the Freebase Dataset

### ISSUE THREAD

**Issue by familyld** [RUCDM/KB4Rec#1]
Hi,  your job on SIGIR-18 is very fascinating and has important realistic significance. However, when I try to reproduce the experiments, I found that there are many uncertainties. For example, in your paper "Improving Sequential Recommendation with Knowledge-Enhanced Memory Networks" , you declared:

> we adopt the one-time Freebase [8] dump consisting of 63 million triples

In "KB4Rec: A Dataset for Linking Knowledge Bases with Recommender Systems", you declared:

> we use the version of March 2015, which is its latest public version.

But what I found on the homepage of Freebase is:

![snipaste_2018-09-14_12-45-13](https://user-images.githubusercontent.com/12497920/45530240-4457cd00-b81c-11e8-820f-72d9a85b9f0a.png)
![snipaste_2018-09-14_12-27-24](https://user-images.githubusercontent.com/12497920/45530239-43bf3680-b81c-11e8-98dc-b8f9fc3a9db2.png)

Which is the actually data set you used for training the KSR algorithm? Or do you use the pre-trained embeddings provided by  the thunlp group? Can you provide some further instructions on how to produce the entity embeddings or **a method to download the embeddings** you used in the experiments? This is an issue of significance to reproduce the experimental results.  Any help will be greatly appreciated.

Thanks you very much.

Best regards.

**Comment by RichardHGL** [comment]
![image](https://user-images.githubusercontent.com/20337906/50720924-ab620000-10f1-11e9-9e3c-4be2fa3199b4.png)
we used this one(latest version)

**Comment by RichardHGL** [comment]
We use embedding trained on subgraph of freebase( train through Fast-TransX). For this, you can refer to https://github.com/BetsyHJ/KSR/tree/master/data for more details.
