### ISSUE TITLE
AssertionError: Checkpoint file not found!

### ISSUE THREAD

**Issue by Zhang-Each** [RUCDM/KB4Rec#10]
Found error when runing UPGAN code, it seems that the pre-trained embeddings are not released. How to solve such problem.

**Comment by Zhang-Each** [comment]
When I Run CUDA_VISIBLE_DEVICES=2 python main_pretrain.py command, the following file is not found.

checkpoint/good_pretrain/book/init/book-DistMult-bce-decay.ckpt

**Comment by RichardHGL** [comment]
Please refer to https://github.com/RichardHGL/UPGAN
