### ISSUE TITLE
得到linkage的代码

### ISSUE THREAD

**Issue by zhaijianyang** [RUCDM/KB4Rec#12]
请问有得到linkage的代码吗

**Comment by RichardHGL** [comment]
这部分的代码我们没有提供，用商品名称和freebase里type.object.name匹配即可;如果需要匹配author或者其他属性，同理，匹配相应的属性实体的name

**Comment by zhaijianyang** [comment]
> 这部分的代码我们没有提供，用商品名称和freebase里type.object.name匹配即可;如果需要匹配author或者其他属性，同理，匹配相应的属性实体的name

好的，谢谢啦
