### ISSUE TITLE
关于linkage的处理

### ISSUE THREAD

**Issue by zhaijianyang** [RUCDM/KB4Rec#13]
您好，我想问下关于数据处理的问题：
1. 在Metadata中，商品具有不同的asin，但是可能有相同的title，比如'0001054783', '0199555648'的title都是The Case Book of Sherlock Holmes，请问在title匹配freebase之后，怎么处理不同的asin呢？
2. 是否会出现匹配不正确的情况？比如一本书的名字和人的名字一样，freebase中没有这本书，会通过实体属性删除这部分错误吗？

**Comment by RichardHGL** [comment]
您好！我们当时处理时是按照名称匹配+属性匹配，书名匹配加作者匹配 (writer name)。不存在匹配上人的情况（人在KB里没有作者属性）。

**Comment by zhaijianyang** [comment]
数据集中不是没有作者信息吗，是用”作者“这个属性，而不是作者名字，是这样吗？

**Comment by RichardHGL** [comment]
当时负责book的同学应该是爬取了author的信息或者从其他关联渠道获得了asin对应author，然后匹配了作者的名字；
