### ISSUE TITLE
regarding item2entity match

### ISSUE THREAD

**Issue by Antoniozxm** [RUCDM/KB4Rec#15]
作者您好，感谢你的工作！有两个问题想要请教下：
1. item和type.object.name匹配问题，想请问作者是有没有推荐的模糊匹配方法 比如一些情况下需要语意消歧；还是可以直接字符比对？
2. 想确认下在得到item匹配的entity之后，子图的构建是把所有含seed entity的三元组都找出来吗？是的话，想请教下后续需要对relation进行筛选吗？不是的话想请问是如何抽取三元组的。
感谢！

**Comment by RichardHGL** [comment]
1. 我们主要进行了字符对比
2. 对，把seed entity的三元组找出来，然后根据感兴趣的关系筛选。抽取三元组子图的代码在expansion folder下

**Comment by Antoniozxm** [comment]
谢谢~
