### ISSUE TITLE
how to recommend for users when there is no user-item interaction data?

### ISSUE THREAD

**Issue by Johnnytjn** [RUCDM/KB4Rec#4]
there is only KG data linked to FreeBase, how can we get the **Interaction** data for these three dataset?

**Comment by RichardHGL** [comment]
These datasets are open-sourced on the Internet. You can just search them in browser.
Such as movielens dataset: https://grouplens.org/datasets/movielens/.
last.fm http://www.cp.jku.at/datasets/LFM-1b/
Amazon datasets http://jmcauley.ucsd.edu/data/amazon/

**Comment by Johnnytjn** [comment]
Thanks



---Original---
