### ISSUE TITLE
 Statistics of our subgraph for training TransE.

### ISSUE THREAD

**Issue by sunnysq** [RUCDM/KB4Rec#9]
您好，您文章 “KB4Rec: A Data Set for Linking Knowledge Bases with Recommender Systems”中用来TransE训练的子图过滤了不常见和通用的关系及其所有相关的 KB 三元组，请问这里的不常见和通用的关系指的是什么，您可以公开Table3数据处理的源码吗？

**Comment by RichardHGL** [comment]
"unfrequent relations" refers to relations which occur less than some threshold (e.g., 10).
"general-purpose relations" refers to some triples which are nearly associated with every entity but may be not of meaning. (e.g, "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>" relations occur for most of Freebase entities.)
Actually, if you try to improve RS with KB, my suggestion to obtain such subgraph through manual relation selection after obtaining 2-hop subgraph for items in RS. 
Actually, the statistics of table 3 are from "Improving Sequential Recommendation with Knowledge-Enhanced Memory Networks". 
Instead of implementing it, I suggest dealing with the KB yourself.

**Comment by sunnysq** [comment]
> "unfrequent relations" refers to relations which occur less than some threshold (e.g., 10).
> "general-purpose relations" refers to some triples which are nearly associated with every entity but may be not of meaning. (e.g, "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" relations occur for most of Freebase entities.)
> Actually, if you try to improve RS with KB, my suggestion to obtain such subgraph through manual relation selection after obtaining 2-hop subgraph for items in RS.
> Actually, the statistics of table 3 are from "Improving Sequential Recommendation with Knowledge-Enhanced Memory Networks".
> Instead of implementing it, I suggest dealing with the KB yourself.

Thank you for your answer. I want to manually select the relationship I need. I found some information, but I still don’t know the meaning of the relationship in freebase.Could you please tell me.I'm looking forward to your reply.

**Comment by RichardHGL** [comment]
Actually, I'm also unclear about all freebase relation semantics, I try to understand them as domain/sub_domain/topic. But you can follow some simple tricks to select relations:
(1) Take movie as an example, relation start with film may be more relevant relations.
(2) Rank other relations according to occurrence with seed entity set (items maybe), and manually check their semantics and some sample triple.
(3) Delete relations which connect to string like some key about movie, link about website
Hope it works for you!

**Comment by sunnysq** [comment]
Thanks! I will try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RUCDM/KB4Rec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RUCDM/KB4Rec]  Statistics of our subgraph for training TransE. (#9)





 
Actually, I'm not also clear about all its semantics. But you can follow some simple tricks to select relations:
 (1) Take movie as an example, relation start with film may be more relevant relations.
 (2) Rank other relations according to occurrence with seed entity set (items maybe), and manually check their semantics and some sample triple.
 (3) Delete relations which connect to string like some key about movie, link about website
 Hope it works for you!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
